package com.cyclosa.discipline.enums;

public enum DismissalGround {
    THEFT_FRAUD_GAMBLING_ASSAULT_DRUGS,
    TRADE_SECRET_IP_SERIOUS_DAMAGE_HARASSMENT,
    REPEAT_VIOLATION_DURING_ACTIVE_DISCIPLINE,
    UNAUTHORIZED_ABSENCE
}
